adding Helicopter class with methods
smykandriy/python-labs-2023 pull request #1
Opened 2023-05-11 14:56 UTC by smykandriy

2023-05-12 09:23 UTC, MarkoYaminsky approved these changes
good as for lab. But not everything is perfectly clean

2023-05-12 09:23 UTC, MarkoYaminsky commented on helicopter.py
> +        Current fuel: {self.current_fuel}"""
Make this with self.__docs__ and loop

2023-05-12 09:23 UTC, MarkoYaminsky commented on helicopter.py
> +            raise ValueError("Invalid altitude value: altitude cannot be negative.")
same ValueError with exact same message is raised twice. You can make a function or even inherit from Exception and make this exact Error (i.e. HelicopterNegativeAltitudeError) without specifying message or with this message as default arg

2023-05-14 14:51 UTC, MarkoYaminsky requested changes

2023-05-14 14:51 UTC, MarkoYaminsky commented on helicopter.py
> +        docstring = [f"{key.capitalize()}: {attrs[key]}" for key in attrs]
This is not docstring, this is attribute dictionary. Who is the one, that originated this idea? I see this 3rd time today

2023-05-14 14:51 UTC, MarkoYaminsky commented on helicopter.py
> +        }
Use \_\_dict\_\_

2023-05-14 14:51 UTC, MarkoYaminsky commented on helicopter.py
> +        print(_)
Андрій, я тебе прибʼю за цей код в файлі з класом, а не в мейні

2023-05-14 14:56 UTC, smykandriy commented on helicopter.py
> +        print(_)
пан Яцук такий приклад показував на лекції, я зробив рівно так само

2023-05-14 15:35 UTC, MarkoYaminsky commented on helicopter.py
> +        attrs = [f"{key.split(sep='_')[-1]}: {self.__dict__[key]}" for key in self.__dict__]
do not invoke \_\_dict\_\_ more than necessary. Make variable attr_dict = self.\_\_dict\_\_ and then use it two times in comprehension

2023-05-14 15:39 UTC, MarkoYaminsky approved these changes
good boy

2023-05-15 21:37 UTC, merged